export default {
  modules: [
    {
      source: "src/report/dot/default-theme.js",
      dependencies: [],
      dependents: ["src/report/dot/theming.js"],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/dot.template.js",
      dependencies: [],
      dependents: ["src/report/dot/index.js"],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/index.js",
      dependencies: [
        {
          dynamic: false,
          module: "./dot.template",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/dot.template.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
        {
          dynamic: false,
          module: "./module-utl",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/module-utl.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
        {
          dynamic: false,
          module: "./prepare-custom-level",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/prepare-custom-level.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
        {
          dynamic: false,
          module: "./prepare-flat-level",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/prepare-flat-level.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
        {
          dynamic: false,
          module: "./prepare-folder-level",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/prepare-folder-level.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
        {
          dynamic: false,
          module: "./theming",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/theming.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: [],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/module-utl.js",
      dependencies: [
        {
          dynamic: false,
          module: "./theming",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/theming.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: [
        "src/report/dot/index.js",
        "src/report/dot/prepare-custom-level.js",
        "src/report/dot/prepare-flat-level.js",
        "src/report/dot/prepare-folder-level.js",
      ],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/theming.js",
      dependencies: [
        {
          dynamic: false,
          module: "./default-theme",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/default-theme.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: ["src/report/dot/index.js", "src/report/dot/module-utl.js"],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/prepare-custom-level.js",
      dependencies: [
        {
          dynamic: false,
          module: "./module-utl",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/module-utl.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: ["src/report/dot/index.js"],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/prepare-flat-level.js",
      dependencies: [
        {
          dynamic: false,
          module: "./module-utl",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/module-utl.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: ["src/report/dot/index.js"],
      orphan: false,
      valid: true,
    },
    {
      source: "src/report/dot/prepare-folder-level.js",
      dependencies: [
        {
          dynamic: false,
          module: "./module-utl",
          moduleSystem: "cjs",
          exoticallyRequired: false,
          resolved: "src/report/dot/module-utl.js",
          coreModule: false,
          followable: true,
          couldNotResolve: false,
          dependencyTypes: ["local"],
          matchesDoNotFollow: false,
          circular: false,
          valid: true,
        },
      ],
      dependents: ["src/report/dot/index.js"],
      orphan: false,
      valid: true,
    },
  ],
  summary: {
    violations: [],
    error: 0,
    warn: 0,
    info: 0,
    ignore: 0,
    totalCruised: 8,
    totalDependenciesCruised: 11,
    optionsUsed: {
      combinedDependencies: false,
      doNotFollow: {
        path: "node_modules",
      },
      exclude: {
        path: "mocks|fixtures|test/integration|src/cli/tools/svg-in-html-snippets/script.snippet.js",
      },
      externalModuleResolutionStrategy: "node_modules",
      includeOnly: "^src/report/dot",
      moduleSystems: ["cjs", "es6"],
      outputTo: "-",
      outputType: "json",
      preserveSymlinks: false,
      rulesFile: ".dependency-cruiser.json",
      tsPreCompilationDeps: true,
      exoticRequireStrings: ["tryRequire", "requireJSON"],
      enhancedResolveOptions: {
        exportsFields: ["exports"],
        conditionNames: ["require"],
        extensions: [".js", ".d.ts"],
      },
      args: "src/report/dot",
    },
    ruleSetUsed: {
      forbidden: [
        {
          name: "utl-module-not-shared-enough",
          comment: "(sample rule to demo demo rules based on dependents)",
          severity: "info",
          from: {
            path: "^src",
          },
          module: {
            path: "^src/utl",
            numberOfDependentsLessThan: 3,
          },
        },
      ],
    },
  },
};
