version: "2"
checks:
  method-lines:
    config:
      threshold: 32
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc.json
    checks:
      # compat is not a codeclimeate supported eslint plugin
      compat/compat:
        enabled: false
exclude_patterns:
  - ".github/"
  - "configs/"
  - "doc/"
  - "docs/"
  - "test/"
  - "types/"
  - "utl/"
  - "**/node_modules/"
  - "src/report/**/*.template.js"
