version: "2"
checks:
  method-complexity:
    config:
      threshold: 7
  method-lines:
    config:
      threshold: 36
# removed the eslint plugin. The eslint ecosystem moves faster
# than what codeclimate can keep up with - and we're running
# eslint on other ci platforms anyway now.
exclude_patterns:
  - ".github/"
  - "configs/"
  - "doc/"
  - "docs/"
  - "test/"
  - "types/"
  - "tools/"
  - "**/node_modules/"
  - "src/report/**/*.template.js"
  - "src/**/*.schema.mjs"
