flowchart LR

subgraph bin["bin"]
  bindependency-cruise["dependency-cruise"]
end
packagejson["package.json"]
subgraph node_modules["node_modules"]
  subgraph node_modulescommander["commander"]
    node_modulescommanderindexjs["index.js"]
  end
  subgraph node_modulessemver["semver"]
    node_modulessemversemverjs["semver.js"]
  end
  subgraph node_modulesglob["glob"]
    node_modulesglobglobjs["glob.js"]
  end
  subgraph node_moduleslodash["lodash"]
    node_moduleslodashgetjs["get.js"]
    node_moduleslodashlodashjs["lodash.js"]
    node_moduleslodashmemoizejs["memoize.js"]
    node_moduleslodashclonejs["clone.js"]
    node_moduleslodashuniqjs["uniq.js"]
    node_moduleslodashflattenDeepjs["flattenDeep.js"]
    node_moduleslodashuniqByjs["uniqBy.js"]
    node_moduleslodashsetjs["set.js"]
    node_moduleslodashisEqualjs["isEqual.js"]
    node_moduleslodashuniqWithjs["uniqWith.js"]
  end
  subgraph node_modulesacorn-walk["acorn-walk"]
    subgraph node_modulesacorn-walkdist["dist"]
      node_modulesacorn-walkdistwalkjs["walk.js"]
    end
  end
  subgraph node_modulessemver-try-require["semver-try-require"]
    subgraph node_modulessemver-try-requiresrc["src"]
      node_modulessemver-try-requiresrcindexjs["index.js"]
    end
  end
  subgraph node_modulesacorn["acorn"]
    subgraph node_modulesacorndist["dist"]
      node_modulesacorndistacornjs["acorn.js"]
    end
  end
  subgraph node_modulesacorn-loose["acorn-loose"]
    subgraph node_modulesacorn-loosedist["dist"]
      node_modulesacorn-loosedistacorn-loosejs["acorn-loose.js"]
    end
  end
  subgraph node_modulesresolve["resolve"]
    node_modulesresolveindexjs["index.js"]
  end
  subgraph node_modulesenhanced-resolve["enhanced-resolve"]
    subgraph node_modulesenhanced-resolvelib["lib"]
      node_modulesenhanced-resolvelibnodejs["node.js"]
    end
  end
  subgraph node_modulesawesome-typescript-loader["awesome-typescript-loader"]
    subgraph node_modulesawesome-typescript-loaderdist["dist"]
      node_modulesawesome-typescript-loaderdistentryjs["entry.js"]
    end
  end
  subgraph node_moduleshandlebars["handlebars"]
    node_moduleshandlebarsruntimejs["runtime.js"]
  end
  subgraph node_moduleschalk["chalk"]
    node_moduleschalkindexjs["index.js"]
  end
  subgraph node_modulesfigures["figures"]
    node_modulesfiguresindexjs["index.js"]
  end
  subgraph node_modulessafe-regex["safe-regex"]
    node_modulessafe-regexindexjs["index.js"]
  end
  subgraph node_modulesajv["ajv"]
    subgraph node_modulesajvlib["lib"]
      node_modulesajvlibajvjs["ajv.js"]
    end
  end
  subgraph node_modulesinquirer["inquirer"]
    subgraph node_modulesinquirerlib["lib"]
      node_modulesinquirerlibinquirerjs["inquirer.js"]
    end
  end
  subgraph node_modulesstrip-json-comments["strip-json-comments"]
    node_modulesstrip-json-commentsindexjs["index.js"]
  end
end
subgraph src["src"]
  subgraph srccli["cli"]
    srccliindexjs["index.js"]
    srccliformatMetaInfojs["formatMetaInfo.js"]
    srccligetResolveConfigjs["getResolveConfig.js"]
    subgraph srccliutl["utl"]
      srccliutlmakeAbsolutejs["makeAbsolute.js"]
      srccliutliojs["io.js"]
      srccliutlvalidateFileExistencejs["validateFileExistence.js"]
    end
    subgraph srccliinitConfig["initConfig"]
      srccliinitConfigindexjs["index.js"]
      srccliinitConfigcreateConfigFilejs["createConfigFile.js"]
      srccliinitConfigconfigjstemplatejs["config.js.template.js"]
      srccliinitConfigconfigjsontemplatejs["config.json.template.js"]
      srccliinitConfiggetUserInputjs["getUserInput.js"]
    end
    srcclinormalizeOptionsjs["normalizeOptions.js"]
    srcclidefaultsjson["defaults.json"]
    subgraph srcclicompileConfig["compileConfig"]
      srcclicompileConfigindexjs["index.js"]
      srcclicompileConfigmergeConfigsjs["mergeConfigs.js"]
      srcclicompileConfigreadConfigjs["readConfig.js"]
    end
    srccliparseTSConfigjs["parseTSConfig.js"]
  end
  subgraph srcmain["main"]
    srcmainindexjs["index.js"]
    subgraph srcmainoptions["options"]
      srcmainoptionsnormalizejs["normalize.js"]
      srcmainoptionsdefaultsjson["defaults.json"]
      srcmainoptionsvalidatejs["validate.js"]
    end
    subgraph srcmainruleSet["ruleSet"]
      srcmainruleSetnormalizejs["normalize.js"]
      srcmainruleSetvalidatejs["validate.js"]
      srcmainruleSetjsonschemajson["jsonschema.json"]
    end
  end
  subgraph srcreport["report"]
    subgraph srcreportdot["dot"]
      srcreportdotrichModuleColorSchemejson["richModuleColorScheme.json"]
      srcreportdotcoloringjs["coloring.js"]
      srcreportdotdefaultModuleColorSchemejson["defaultModuleColorScheme.json"]
      srcreportdotindexjs["index.js"]
      srcreportdotdottemplatejs["dot.template.js"]
    end
    subgraph srcreportcsv["csv"]
      srcreportcsvindexjs["index.js"]
      srcreportcsvcsvtemplatejs["csv.template.js"]
    end
    srcreportdependencyToIncidenceTransformerjs["dependencyToIncidenceTransformer.js"]
    subgraph srcreportddot["ddot"]
      srcreportddotindexjs["index.js"]
      srcreportddotddottemplatejs["ddot.template.js"]
    end
    srcreporterrjs["err.js"]
    subgraph srcreporthtml["html"]
      srcreporthtmlindexjs["index.js"]
      srcreporthtmlhtmltemplatejs["html.template.js"]
    end
    srcreportjsonjs["json.js"]
  end
  subgraph srcextract["extract"]
    srcextractindexjs["index.js"]
    srcextractaddValidationsjs["addValidations.js"]
    subgraph srcextractderive["derive"]
      subgraph srcextractderivecircular["circular"]
        srcextractderivecircularindexjs["index.js"]
        srcextractderivecirculardependencyEndsUpAtFromjs["dependencyEndsUpAtFrom.js"]
      end
      subgraph srcextractderiveorphan["orphan"]
        srcextractderiveorphanindexjs["index.js"]
        srcextractderiveorphanisOrphanjs["isOrphan.js"]
      end
    end
    srcextractextractjs["extract.js"]
    subgraph srcextractast-extractors["ast-extractors"]
      srcextractast-extractorsextract-AMD-depsjs["extract-AMD-deps.js"]
      srcextractast-extractorsextract-commonJS-depsjs["extract-commonJS-deps.js"]
      srcextractast-extractorsextract-ES6-depsjs["extract-ES6-deps.js"]
      srcextractast-extractorsextract-typescript-depsjs["extract-typescript-deps.js"]
    end
    srcextractignorejs["ignore.js"]
    subgraph srcextractparse["parse"]
      srcextractparsetoJavascriptASTjs["toJavascriptAST.js"]
      srcextractparsetoTypescriptASTjs["toTypescriptAST.js"]
    end
    subgraph srcextracttranspile["transpile"]
      srcextracttranspileindexjs["index.js"]
      srcextracttranspilemetajs["meta.js"]
      srcextracttranspilecoffeeWrapjs["coffeeWrap.js"]
      srcextracttranspilejavaScriptWrapjs["javaScriptWrap.js"]
      srcextracttranspileliveScriptWrapjs["liveScriptWrap.js"]
      srcextracttranspiletypeScriptWrapjs["typeScriptWrap.js"]
    end
    subgraph srcextractutl["utl"]
      srcextractutlgetExtensionjs["getExtension.js"]
      srcextractutlpathToPosixjs["pathToPosix.js"]
    end
    subgraph srcextractresolve["resolve"]
      srcextractresolveindexjs["index.js"]
      srcextractresolveresolve-AMDjs["resolve-AMD.js"]
      srcextractresolvedetermineDependencyTypesjs["determineDependencyTypes.js"]
      srcextractresolvelocalNpmHelpersjs["localNpmHelpers.js"]
      srcextractresolveresolvejs["resolve.js"]
      srcextractresolvecompileResolveOptionsjs["compileResolveOptions.js"]
      subgraph srcextractresolvereadPackageDeps["readPackageDeps"]
        srcextractresolvereadPackageDepsindexjs["index.js"]
        srcextractresolvereadPackageDepsmergePackagesjs["mergePackages.js"]
      end
      srcextractresolveresolve-helpersjs["resolve-helpers.js"]
      srcextractresolveresolve-commonJSjs["resolve-commonJS.js"]
      srcextractresolveisFollowablejs["isFollowable.js"]
    end
    srcextractgatherInitialSourcesjs["gatherInitialSources.js"]
    srcextractsummarizejs["summarize.js"]
  end
  subgraph srcvalidate["validate"]
    srcvalidateindexjs["index.js"]
    srcvalidatematchDependencyRulejs["matchDependencyRule.js"]
    srcvalidateisModuleOnlyRulejs["isModuleOnlyRule.js"]
    srcvalidatematchModuleRulejs["matchModuleRule.js"]
  end
end
path["path"]
fs["fs"]
bindependency-cruise --> packagejson
bindependency-cruise --> srccliindexjs
bindependency-cruise --> node_modulescommanderindexjs
bindependency-cruise --> node_modulessemversemverjs
srccliindexjs --> srcmainindexjs
srccliindexjs --> srccliformatMetaInfojs
srccliindexjs --> srccligetResolveConfigjs
srccliindexjs --> srccliinitConfigindexjs
srccliindexjs --> srcclinormalizeOptionsjs
srccliindexjs --> srccliparseTSConfigjs
srccliindexjs --> srccliutliojs
srccliindexjs --> srccliutlvalidateFileExistencejs
srccliindexjs --> node_modulesglobglobjs
srccliindexjs --> node_moduleslodashgetjs
srcmainindexjs --> srcextractindexjs
srcmainindexjs --> srcextracttranspilemetajs
srcmainindexjs --> srcreportcsvindexjs
srcmainindexjs --> srcreportddotindexjs
srcmainindexjs --> srcreportdotindexjs
srcmainindexjs --> srcreportdotrichModuleColorSchemejson
srcmainindexjs --> srcreporterrjs
srcmainindexjs --> srcreporthtmlindexjs
srcmainindexjs --> srcreportjsonjs
srcmainindexjs --> srcmainoptionsnormalizejs
srcmainindexjs --> srcmainoptionsvalidatejs
srcmainindexjs --> srcmainruleSetnormalizejs
srcmainindexjs --> srcmainruleSetvalidatejs
srcextractindexjs --> srcextractaddValidationsjs
srcextractindexjs --> srcextractderivecircularindexjs
srcextractindexjs --> srcextractderiveorphanindexjs
srcextractindexjs --> srcextractextractjs
srcextractindexjs --> srcextractgatherInitialSourcesjs
srcextractindexjs --> srcextractsummarizejs
srcextractindexjs --> srcextractutlpathToPosixjs
srcextractindexjs --> node_moduleslodashlodashjs
srcextractaddValidationsjs --> srcvalidateindexjs
srcvalidateindexjs --> srcvalidatematchDependencyRulejs
srcvalidateindexjs --> srcvalidatematchModuleRulejs
srcvalidatematchDependencyRulejs --> srcvalidateisModuleOnlyRulejs
srcvalidatematchModuleRulejs --> srcvalidateisModuleOnlyRulejs
srcextractderivecircularindexjs --> srcextractderivecirculardependencyEndsUpAtFromjs
srcextractderivecircularindexjs --> node_moduleslodashgetjs
srcextractderiveorphanindexjs --> srcextractderiveorphanisOrphanjs
srcextractderiveorphanindexjs --> node_moduleslodashgetjs
srcextractextractjs --> srcextractast-extractorsextract-AMD-depsjs
srcextractextractjs --> srcextractast-extractorsextract-ES6-depsjs
srcextractextractjs --> srcextractast-extractorsextract-commonJS-depsjs
srcextractextractjs --> srcextractast-extractorsextract-typescript-depsjs
srcextractextractjs --> srcextractignorejs
srcextractextractjs --> srcextractparsetoJavascriptASTjs
srcextractextractjs --> srcextractparsetoTypescriptASTjs
srcextractextractjs --> srcextractresolveindexjs
srcextractextractjs --> node_moduleslodashlodashjs
srcextractextractjs --> path
srcextractast-extractorsextract-AMD-depsjs --> srcextractast-extractorsextract-commonJS-depsjs
srcextractast-extractorsextract-AMD-depsjs --> node_modulesacorn-walkdistwalkjs
srcextractast-extractorsextract-commonJS-depsjs --> node_modulesacorn-walkdistwalkjs
srcextractast-extractorsextract-ES6-depsjs --> node_modulesacorn-walkdistwalkjs
srcextractast-extractorsextract-typescript-depsjs --> packagejson
srcextractast-extractorsextract-typescript-depsjs --> node_modulessemver-try-requiresrcindexjs
srcextractparsetoJavascriptASTjs --> srcextracttranspileindexjs
srcextractparsetoJavascriptASTjs --> srcextractutlgetExtensionjs
srcextractparsetoJavascriptASTjs --> node_modulesacorndistacornjs
srcextractparsetoJavascriptASTjs --> node_modulesacorn-loosedistacorn-loosejs
srcextractparsetoJavascriptASTjs --> fs
srcextractparsetoJavascriptASTjs --> node_moduleslodashmemoizejs
srcextracttranspileindexjs --> srcextracttranspilemetajs
srcextracttranspilemetajs --> packagejson
srcextracttranspilemetajs --> srcextracttranspilecoffeeWrapjs
srcextracttranspilemetajs --> srcextracttranspilejavaScriptWrapjs
srcextracttranspilemetajs --> srcextracttranspileliveScriptWrapjs
srcextracttranspilemetajs --> srcextracttranspiletypeScriptWrapjs
srcextracttranspilecoffeeWrapjs --> packagejson
srcextracttranspilecoffeeWrapjs --> node_modulessemver-try-requiresrcindexjs
srcextracttranspileliveScriptWrapjs --> packagejson
srcextracttranspileliveScriptWrapjs --> node_modulessemver-try-requiresrcindexjs
srcextracttranspiletypeScriptWrapjs --> packagejson
srcextracttranspiletypeScriptWrapjs --> node_moduleslodashgetjs
srcextracttranspiletypeScriptWrapjs --> node_modulessemver-try-requiresrcindexjs
srcextractutlgetExtensionjs --> path
srcextractparsetoTypescriptASTjs --> packagejson
srcextractparsetoTypescriptASTjs --> fs
srcextractparsetoTypescriptASTjs --> node_moduleslodashmemoizejs
srcextractparsetoTypescriptASTjs --> node_modulessemver-try-requiresrcindexjs
srcextractresolveindexjs --> srcextractutlpathToPosixjs
srcextractresolveindexjs --> srcextractresolveresolve-AMDjs
srcextractresolveindexjs --> srcextractresolveresolve-commonJSjs
srcextractresolveindexjs --> fs
srcextractresolveindexjs --> path
srcextractutlpathToPosixjs --> path
srcextractresolveresolve-AMDjs --> srcextractutlpathToPosixjs
srcextractresolveresolve-AMDjs --> srcextractresolvedetermineDependencyTypesjs
srcextractresolveresolve-AMDjs --> srcextractresolvereadPackageDepsindexjs
srcextractresolveresolve-AMDjs --> srcextractresolveresolve-helpersjs
srcextractresolveresolve-AMDjs --> fs
srcextractresolveresolve-AMDjs --> node_moduleslodashmemoizejs
srcextractresolveresolve-AMDjs --> path
srcextractresolveresolve-AMDjs --> node_modulesresolveindexjs
srcextractresolvedetermineDependencyTypesjs --> srcextractresolvelocalNpmHelpersjs
srcextractresolvedetermineDependencyTypesjs --> path
srcextractresolvedetermineDependencyTypesjs --> node_modulesresolveindexjs
srcextractresolvelocalNpmHelpersjs --> srcextractresolveresolvejs
srcextractresolvelocalNpmHelpersjs --> fs
srcextractresolvelocalNpmHelpersjs --> node_moduleslodashmemoizejs
srcextractresolvelocalNpmHelpersjs --> path
srcextractresolveresolvejs --> srcextractutlpathToPosixjs
srcextractresolveresolvejs --> srcextractresolvecompileResolveOptionsjs
srcextractresolveresolvejs --> node_modulesenhanced-resolvelibnodejs
srcextractresolvecompileResolveOptionsjs --> srcextracttranspilemetajs
srcextractresolvecompileResolveOptionsjs --> node_modulesawesome-typescript-loaderdistentryjs
srcextractresolvecompileResolveOptionsjs --> node_modulesenhanced-resolvelibnodejs
srcextractresolvereadPackageDepsindexjs --> srcextractresolvereadPackageDepsmergePackagesjs
srcextractresolvereadPackageDepsindexjs --> fs
srcextractresolvereadPackageDepsindexjs --> node_moduleslodashmemoizejs
srcextractresolvereadPackageDepsindexjs --> path
srcextractresolvereadPackageDepsmergePackagesjs --> node_moduleslodashclonejs
srcextractresolvereadPackageDepsmergePackagesjs --> node_moduleslodashgetjs
srcextractresolvereadPackageDepsmergePackagesjs --> node_moduleslodashuniqjs
srcextractresolveresolve-helpersjs --> srcextractresolvelocalNpmHelpersjs
srcextractresolveresolve-commonJSjs --> srcextractutlpathToPosixjs
srcextractresolveresolve-commonJSjs --> srcextractresolvedetermineDependencyTypesjs
srcextractresolveresolve-commonJSjs --> srcextractresolveisFollowablejs
srcextractresolveresolve-commonJSjs --> srcextractresolvereadPackageDepsindexjs
srcextractresolveresolve-commonJSjs --> srcextractresolveresolvejs
srcextractresolveresolve-commonJSjs --> srcextractresolveresolve-helpersjs
srcextractresolveresolve-commonJSjs --> path
srcextractresolveresolve-commonJSjs --> node_modulesresolveindexjs
srcextractresolveisFollowablejs --> srcextractutlgetExtensionjs
srcextractresolveisFollowablejs --> srcextractresolvecompileResolveOptionsjs
srcextractgatherInitialSourcesjs --> srcextractignorejs
srcextractgatherInitialSourcesjs --> srcextracttranspilemetajs
srcextractgatherInitialSourcesjs --> fs
srcextractgatherInitialSourcesjs --> node_modulesglobglobjs
srcextractgatherInitialSourcesjs --> path
srcextractsummarizejs --> node_moduleslodashflattenDeepjs
srcreportcsvindexjs --> srcreportdependencyToIncidenceTransformerjs
srcreportcsvindexjs --> srcreportcsvcsvtemplatejs
srcreportcsvindexjs --> node_moduleshandlebarsruntimejs
srcreportcsvcsvtemplatejs --> node_moduleshandlebarsruntimejs
srcreportddotindexjs --> srcreportdotcoloringjs
srcreportddotindexjs --> srcreportddotddottemplatejs
srcreportddotindexjs --> node_moduleshandlebarsruntimejs
srcreportddotindexjs --> node_moduleslodashclonejs
srcreportddotindexjs --> node_moduleslodashgetjs
srcreportddotindexjs --> node_moduleslodashuniqByjs
srcreportddotindexjs --> path
srcreportdotcoloringjs --> srcreportdotdefaultModuleColorSchemejson
srcreportdotcoloringjs --> node_moduleslodashgetjs
srcreportddotddottemplatejs --> node_moduleshandlebarsruntimejs
srcreportdotindexjs --> srcreportdotcoloringjs
srcreportdotindexjs --> srcreportdotdottemplatejs
srcreportdotindexjs --> node_moduleshandlebarsruntimejs
srcreportdotindexjs --> path
srcreportdotdottemplatejs --> node_moduleshandlebarsruntimejs
srcreporterrjs --> node_moduleschalkindexjs
srcreporterrjs --> node_modulesfiguresindexjs
srcreporthtmlindexjs --> srcreportdependencyToIncidenceTransformerjs
srcreporthtmlindexjs --> srcreporthtmlhtmltemplatejs
srcreporthtmlindexjs --> node_moduleshandlebarsruntimejs
srcreporthtmlhtmltemplatejs --> node_moduleshandlebarsruntimejs
srcmainoptionsnormalizejs --> srcmainoptionsdefaultsjson
srcmainoptionsvalidatejs --> node_modulessafe-regexindexjs
srcmainruleSetvalidatejs --> srcmainoptionsvalidatejs
srcmainruleSetvalidatejs --> srcmainruleSetjsonschemajson
srcmainruleSetvalidatejs --> node_modulesajvlibajvjs
srcmainruleSetvalidatejs --> node_modulessafe-regexindexjs
srccliformatMetaInfojs --> srcmainindexjs
srccliformatMetaInfojs --> node_moduleschalkindexjs
srccliformatMetaInfojs --> node_modulesfiguresindexjs
srccligetResolveConfigjs --> srccliutlmakeAbsolutejs
srccliutlmakeAbsolutejs --> path
srccliinitConfigindexjs --> srccliinitConfigcreateConfigFilejs
srccliinitConfigindexjs --> srccliinitConfiggetUserInputjs
srccliinitConfigcreateConfigFilejs --> packagejson
srccliinitConfigcreateConfigFilejs --> srccliinitConfigconfigjstemplatejs
srccliinitConfigcreateConfigFilejs --> srccliinitConfigconfigjsontemplatejs
srccliinitConfigcreateConfigFilejs --> fs
srccliinitConfigcreateConfigFilejs --> node_moduleshandlebarsruntimejs
srccliinitConfigconfigjstemplatejs --> node_moduleshandlebarsruntimejs
srccliinitConfigconfigjsontemplatejs --> node_moduleshandlebarsruntimejs
srccliinitConfiggetUserInputjs --> node_modulesinquirerlibinquirerjs
srcclinormalizeOptionsjs --> srcclicompileConfigindexjs
srcclinormalizeOptionsjs --> srcclidefaultsjson
srcclinormalizeOptionsjs --> fs
srcclinormalizeOptionsjs --> node_moduleslodashclonejs
srcclinormalizeOptionsjs --> node_moduleslodashgetjs
srcclinormalizeOptionsjs --> node_moduleslodashsetjs
srcclinormalizeOptionsjs --> path
srcclicompileConfigindexjs --> srcextractresolveresolvejs
srcclicompileConfigindexjs --> srcclicompileConfigmergeConfigsjs
srcclicompileConfigindexjs --> srcclicompileConfigreadConfigjs
srcclicompileConfigindexjs --> path
srcclicompileConfigmergeConfigsjs --> node_moduleslodashgetjs
srcclicompileConfigmergeConfigsjs --> node_moduleslodashisEqualjs
srcclicompileConfigmergeConfigsjs --> node_moduleslodashuniqByjs
srcclicompileConfigmergeConfigsjs --> node_moduleslodashuniqWithjs
srcclicompileConfigreadConfigjs --> fs
srcclicompileConfigreadConfigjs --> path
srcclicompileConfigreadConfigjs --> node_modulesstrip-json-commentsindexjs
srccliparseTSConfigjs --> packagejson
srccliparseTSConfigjs --> node_moduleslodashgetjs
srccliparseTSConfigjs --> path
srccliparseTSConfigjs --> node_modulessemver-try-requiresrcindexjs
srccliutliojs --> fs
srccliutlvalidateFileExistencejs --> fs
