flowchart LR

subgraph test["test"]
  subgraph testcli["cli"]
    subgraph testclifixtures["fixtures"]
      subgraph testclifixturesunresolvable-in-sub["unresolvable-in-sub"]
        testclifixturesunresolvable-in-subrefers-to-a-do-not-follow-modulejs["refers-to-a-do-not-follow-module.js"]
      end
    end
  end
end
dontFollowThis["dontFollowThis"]
testclifixturesunresolvable-in-subrefers-to-a-do-not-follow-modulejs --> dontFollowThis
