flowchart LR

subgraph test["test"]
  subgraph test_cli["cli"]
    subgraph test_cli_fixtures["fixtures"]
      subgraph test_cli_fixtures_unresolvable-in-sub["unresolvable-in-sub"]
        test_cli_fixtures_unresolvable-in-sub_refers-to-a-do-not-follow-module_js["refers-to-a-do-not-follow-module.js"]
      end
    end
  end
end
dontFollowThis["dontFollowThis"]
test_cli_fixtures_unresolvable-in-sub_refers-to-a-do-not-follow-module_js --> dontFollowThis
