flowchart LR

subgraph node_modules["node_modules"]
  subgraph node_modules_somemodule["somemodule"]
    subgraph node_modules_somemodule_node_modules["node_modules"]
      subgraph node_modules_somemodule_node_modules_someothermodule["someothermodule"]
        node_modules_somemodule_node_modules_someothermodule_main_js["main.js"]
      end
    end
    subgraph node_modules_somemodule_src["src"]
      node_modules_somemodule_src_moar_javascript_js["moar-javascript.js"]
      node_modules_somemodule_src_somemodule_js["somemodule.js"]
    end
  end
end
one_only_one_js["one_only_one.js"]
path["path"]
one_only_two_js["one_only_two.js"]
root_one_js["root_one.js"]
fs["fs"]
shared_js["shared.js"]
subgraph sub["sub"]
  sub_dir_js["dir.js"]
  sub_depindir_js["depindir.js"]
end
root_two_js["root_two.js"]
somedata_json["somedata.json"]
http["http"]
two_only_one_js["two_only_one.js"]
node_modules_somemodule_src_somemodule_js-->node_modules_somemodule_src_moar_javascript_js
node_modules_somemodule_src_somemodule_js-->node_modules_somemodule_node_modules_someothermodule_main_js
one_only_one_js-->path
one_only_two_js-->path
root_one_js-->one_only_one_js
root_one_js-->one_only_two_js
root_one_js-->shared_js
root_one_js-->sub_dir_js
root_one_js-->fs
root_one_js-->node_modules_somemodule_src_somemodule_js
shared_js-->path
sub_dir_js-->sub_depindir_js
sub_dir_js-->path
sub_depindir_js-->path
root_two_js-->shared_js
root_two_js-->somedata_json
root_two_js-->two_only_one_js
root_two_js-->http
two_only_one_js-->sub_dir_js
