flowchart LR

subgraph 0["bin"]
1["dependency-cruise"]
end
2["package.json"]
subgraph 3["node_modules"]
subgraph 4["commander"]
5["index.js"]
end
subgraph 6["semver"]
7["semver.js"]
end
subgraph b["glob"]
c["glob.js"]
end
subgraph d["lodash"]
e["get.js"]
m["lodash.js"]
1n["memoize.js"]
2h["clone.js"]
2i["uniq.js"]
2o["flattenDeep.js"]
2x["uniqBy.js"]
44["set.js"]
48["isEqual.js"]
49["uniqWith.js"]
end
subgraph 14["acorn-walk"]
subgraph 15["dist"]
16["walk.js"]
end
end
subgraph 1a["semver-try-require"]
subgraph 1b["src"]
1c["index.js"]
end
end
subgraph 1g["acorn"]
subgraph 1h["dist"]
1i["acorn.js"]
end
end
subgraph 1j["acorn-loose"]
subgraph 1k["dist"]
1l["acorn-loose.js"]
end
end
subgraph 22["resolve"]
23["index.js"]
end
subgraph 27["enhanced-resolve"]
subgraph 28["lib"]
29["node.js"]
end
end
subgraph 2b["awesome-typescript-loader"]
subgraph 2c["dist"]
2d["entry.js"]
end
end
subgraph 2r["handlebars"]
2s["runtime.js"]
end
subgraph 34["chalk"]
35["index.js"]
end
subgraph 36["figures"]
37["index.js"]
end
subgraph 3g["safe-regex"]
3h["index.js"]
end
subgraph 3m["ajv"]
subgraph 3n["lib"]
3o["ajv.js"]
end
end
subgraph 3z["inquirer"]
subgraph 40["lib"]
41["inquirer.js"]
end
end
subgraph 4b["strip-json-comments"]
4c["index.js"]
end
end
subgraph 8["src"]
subgraph 9["cli"]
a["index.js"]
3p["formatMetaInfo.js"]
3q["getResolveConfig.js"]
subgraph 3r["utl"]
3s["makeAbsolute.js"]
4e["io.js"]
4f["validateFileExistence.js"]
end
subgraph 3t["initConfig"]
3u["index.js"]
3v["createConfigFile.js"]
3w["config.js.template.js"]
3x["config.json.template.js"]
3y["getUserInput.js"]
end
42["normalizeOptions.js"]
43["defaults.json"]
subgraph 45["compileConfig"]
46["index.js"]
47["mergeConfigs.js"]
4a["readConfig.js"]
end
4d["parseTSConfig.js"]
end
subgraph f["main"]
g["index.js"]
subgraph 3c["options"]
3d["normalize.js"]
3e["defaults.json"]
3f["validate.js"]
end
subgraph 3i["ruleSet"]
3j["normalize.js"]
3k["validate.js"]
3l["jsonschema.json"]
end
end
subgraph h["report"]
subgraph i["dot"]
j["richModuleColorScheme.json"]
2y["coloring.js"]
2z["defaultModuleColorScheme.json"]
31["index.js"]
32["dot.template.js"]
end
subgraph 2p["csv"]
2q["index.js"]
2u["csv.template.js"]
end
2t["dependencyToIncidenceTransformer.js"]
subgraph 2v["ddot"]
2w["index.js"]
30["ddot.template.js"]
end
33["err.js"]
subgraph 38["html"]
39["index.js"]
3a["html.template.js"]
end
3b["json.js"]
end
subgraph k["extract"]
l["index.js"]
n["addValidations.js"]
subgraph t["derive"]
subgraph u["circular"]
v["index.js"]
w["dependencyEndsUpAtFrom.js"]
end
subgraph x["orphan"]
y["index.js"]
z["isOrphan.js"]
end
end
10["extract.js"]
subgraph 12["ast-extractors"]
13["extract-AMD-deps.js"]
17["extract-commonJS-deps.js"]
18["extract-ES6-deps.js"]
19["extract-typescript-deps.js"]
end
1d["ignore.js"]
subgraph 1e["parse"]
1f["toJavascriptAST.js"]
1x["toTypescriptAST.js"]
end
subgraph 1o["transpile"]
1p["index.js"]
1q["meta.js"]
1r["coffeeWrap.js"]
1s["javaScriptWrap.js"]
1t["liveScriptWrap.js"]
1u["typeScriptWrap.js"]
end
subgraph 1v["utl"]
1w["getExtension.js"]
20["pathToPosix.js"]
end
subgraph 1y["resolve"]
1z["index.js"]
21["resolve-AMD.js"]
24["determineDependencyTypes.js"]
25["localNpmHelpers.js"]
26["resolve.js"]
2a["compileResolveOptions.js"]
subgraph 2e["readPackageDeps"]
2f["index.js"]
2g["mergePackages.js"]
end
2j["resolve-helpers.js"]
2k["resolve-commonJS.js"]
2l["isFollowable.js"]
end
2m["gatherInitialSources.js"]
2n["summarize.js"]
end
subgraph o["validate"]
p["index.js"]
q["matchDependencyRule.js"]
r["isModuleOnlyRule.js"]
s["matchModuleRule.js"]
end
end
11["path"]
1m["fs"]
1-->2
1-->a
1-->5
1-->7
a-->g
a-->3p
a-->3q
a-->3u
a-->42
a-->4d
a-->4e
a-->4f
a-->c
a-->e
g-->l
g-->1q
g-->2q
g-->2w
g-->31
g-->j
g-->33
g-->39
g-->3b
g-->3d
g-->3f
g-->3j
g-->3k
l-->n
l-->v
l-->y
l-->10
l-->2m
l-->2n
l-->20
l-->m
n-->p
p-->q
p-->s
q-->r
s-->r
v-->w
v-->e
y-->z
y-->e
10-->13
10-->18
10-->17
10-->19
10-->1d
10-->1f
10-->1x
10-->1z
10-->m
10-->11
13-->17
13-->16
17-->16
18-->16
19-->2
19-->1c
1f-->1p
1f-->1w
1f-->1i
1f-->1l
1f-->1m
1f-->1n
1p-->1q
1q-->2
1q-->1r
1q-->1s
1q-->1t
1q-->1u
1r-->2
1r-->1c
1t-->2
1t-->1c
1u-->2
1u-->e
1u-->1c
1w-->11
1x-->2
1x-->1m
1x-->1n
1x-->1c
1z-->20
1z-->21
1z-->2k
1z-->1m
1z-->11
20-->11
21-->20
21-->24
21-->2f
21-->2j
21-->1m
21-->1n
21-->11
21-->23
24-->25
24-->11
24-->23
25-->26
25-->1m
25-->1n
25-->11
26-->20
26-->2a
26-->29
2a-->1q
2a-->2d
2a-->29
2f-->2g
2f-->1m
2f-->1n
2f-->11
2g-->2h
2g-->e
2g-->2i
2j-->25
2k-->20
2k-->24
2k-->2l
2k-->2f
2k-->26
2k-->2j
2k-->11
2k-->23
2l-->1w
2l-->2a
2m-->1d
2m-->1q
2m-->1m
2m-->c
2m-->11
2n-->2o
2q-->2t
2q-->2u
2q-->2s
2u-->2s
2w-->2y
2w-->30
2w-->2s
2w-->2h
2w-->e
2w-->2x
2w-->11
2y-->2z
2y-->e
30-->2s
31-->2y
31-->32
31-->2s
31-->11
32-->2s
33-->35
33-->37
39-->2t
39-->3a
39-->2s
3a-->2s
3d-->3e
3f-->3h
3k-->3f
3k-->3l
3k-->3o
3k-->3h
3p-->g
3p-->35
3p-->37
3q-->3s
3s-->11
3u-->3v
3u-->3y
3v-->2
3v-->3w
3v-->3x
3v-->1m
3v-->2s
3w-->2s
3x-->2s
3y-->41
42-->46
42-->43
42-->1m
42-->2h
42-->e
42-->44
42-->11
46-->26
46-->47
46-->4a
46-->11
47-->e
47-->48
47-->2x
47-->49
4a-->1m
4a-->11
4a-->4c
4d-->2
4d-->e
4d-->11
4d-->1c
4e-->1m
4f-->1m
