flowchart LR

subgraph 0["src"]
subgraph 1["main"]
subgraph 2["rule-set"]
3["normalize.js"]
end
4["index.js"]
subgraph I["utl"]
J["normalize-re-properties.js"]
end
end
end
subgraph 5["test"]
subgraph 6["enrich"]
subgraph 7["derive"]
subgraph 8["reachable"]
9["index.spec.mjs"]
end
end
end
subgraph A["main"]
subgraph B["rule-set"]
C["normalize.spec.mjs"]
end
end
subgraph D["validate"]
E["parse-ruleset.utl.mjs"]
end
end
subgraph F["node_modules"]
subgraph G["lodash"]
H["has.js"]
K["cloneDeep.js"]
end
end
3-->J
3-->K
3-->H
4-->3
9-->3
C-->3
E-->3

style 3 fill:lime,color:black