flowchart LR

subgraph 0["src"]
subgraph 1["main"]
subgraph 2["rule-set"]
3["normalize.js"]
end
4["index.js"]
subgraph i["utl"]
j["normalize-re-properties.js"]
end
end
end
subgraph 5["test"]
subgraph 6["enrich"]
subgraph 7["derive"]
subgraph 8["reachable"]
9["index.spec.mjs"]
end
end
end
subgraph a["main"]
subgraph b["rule-set"]
c["normalize.spec.mjs"]
end
end
subgraph d["validate"]
e["parse-ruleset.utl.mjs"]
end
end
subgraph f["node_modules"]
subgraph g["lodash"]
h["has.js"]
k["cloneDeep.js"]
end
end
3-->j
3-->k
3-->h
4-->3
9-->3
c-->3
e-->3

style 3 fill:lime,color:black