# modules

"aap"."noot"."mies.js": {class: module; style.stroke: orange; tooltip: "ignored-rule
no-orphans
some-other-rule
some-other-rule-again"; link: "aap/noot/mies.js"}

# dependencies



# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
