# modules

"node_modules"."yudelyo"."index.js": {class: module; shape: package; link: "https://www.npmjs.com/package/yudelyo"}

# dependencies



# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
