# modules

"aap"."noot"."mies.js": {class: module; style.fill: yellow; link: "aap/noot/mies.js"}

# dependencies



# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
