# modules

"node_modules"."slodash": {class: module; style.multiple: true; shape: package; link: "https://www.npmjs.com/package/slodash"}

# dependencies



# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
