# modules

"aap"."noot"."mies.js": {class: module; link: "aap/noot/mies.js"}
"aap"."noot"."zus.js": {class: module; link: "aap/noot/zus.js"}

# dependencies

"aap"."noot"."mies.js" -> "aap"."noot"."zus.js": {style: {stroke: orange}; label: "pas-de-alez-houpe"}

# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
