name: yarn berry test - linux

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cache external modules for ${{matrix.node-version}}@${{matrix.platform}}
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            .yarnrc.yml
            .pnp.js
            yarn.lock
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install & build
        run: |
          node --version
          rm -f .npmrc
          yarn set version berry
          YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn
        shell: bash
        env:
          CI: true
      - name: forbidden dependency check
        run: |
          node --version
          yarn --version
          yarn depcruise
        shell: bash
        env:
          CI: true
      # testing doesn't work as the tests are esm and berry, with pnp enabled,
      # doesn't support esm yet.
      # - name: test coverage
      #   run: |
      #     node --version
      #     yarn --version
      #     yarn test:cover
      #   shell: bash
      #   env:
      #     CI: true
