name: yarn pnp integration test

on:
  push:
      branches:
      - master
      - develop
  pull_request:

jobs:
  integration:

    strategy:
      fail-fast: false
      matrix:
        node-version: 
          - 12.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: install
      run: |
        node --version
        npm install
      shell: bash
      env:
        CI: true
    - name: forbidden dependency checks in a yarn pnp environment
      run: |
        node --version
        npm run test:integration
      shell: bash
      env:
        CI: true